services:
  server:
    build:
      dockerfile: ./src/main/docker/Dockerfile.native
      context: ./server
    hostname: server
    restart: unless-stopped

  proxy:
    image: caddy:2.9-alpine
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile:ro
      - type: bind
        source: "/var/lib/rbg-cert/live/host:intum:vmbhatotia106.privkey.pem"
        target: /key.pem
        read_only: true
      - type: bind
        source: "/var/lib/rbg-cert/live/host:intum:vmbhatotia106.fullchain.pem"
        target: /cert.pem
        read_only: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    restart: unless-stopped
