services:
  server:
    build:
      dockerfile: ./src/main/docker/Dockerfile.jvm
      context: ./server
    hostname: server
    restart: unless-stopped
    env_file:
      - server/.env

  zipquery:
    image: tumls1itg/hackatum-25-hestia-zipquery
    hostname: zipquery
    restart: unless-stopped

  client:
    build:
      dockerfile: ./Dockerfile
      context: ./client
    hostname: client
    restart: unless-stopped

  proxy:
    image: caddy:2.9-alpine
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
      - zipquery
      - client
    restart: unless-stopped
